paises_en_pt = {
    "Afghanistan": "Afeganistão",
    "Albania": "Albânia",
    "Algeria": "Argélia",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Argentina": "Argentina",
    "Armenia": "Arménia",
    "Australia": "Austrália",
    "Austria": "Aus A",
    "Azerbaijan": "Azerbaijão",
    "Bahamas": "Bahamas",
    "Bahrain": "Barém",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belarus": "Bielorrússia",
    "Belgium": "Bélgica",
    "Belize": "Belize",
    "Benin": "Benim",
    "Bhutan": "Butão",
    "Bolivia": "Bolívia",
    "Bosnia and Herzegovina": "Bo BB",
    "Botswana": "Botsuana",
    "Brazil": "Brasil",
    "Brunei": "Brunei",
    "Bulgaria": "Bulgária",
    "Burkina Faso": "Burkina",
    "Burundi": "Burundi",
    "Cambodia": "Camboja",
    "Cameroon": "Camarões",
    "Canada": "Canadá",
    "Cape Verde": "Cabo Verde",
    "Central African Republic": "Rep",
    "Chad": "Chade",
    "Chile": "Chile",
    "China": "China",
    "Colombia": "Colômbia",
    "Comoros": "Comores",
    "Congo": "Congo",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croácia",
    "Cuba": "Cuba",
    "Cyprus": "Chipre",
    "Czech Republic": "Rep RRR",
    "Denmark": "Dinamarca",
    "Djibouti": "Djibuti",
    "Dominica": "Domínica",
    "Dominican Republic": "Rep RR",
    "DR Congo": "Rep R",
    "Ecuador": "Equador",
    "Egypt": "Egito",
    "El Salvador": "El",
    "England": "Inglaterra",
    "Equatorial Guinea": "Guiné G",
    "Eritrea": "Eritreia",
    "Estonia": "Estónia",
    "Eswatini": "Essuatíni",
    "Ethiopia": "Etiópia",
    "Faroe Islands": "Ilhas I I",
    "Fiji": "Fiji",
    "Finland": "Finlândia",
    "France": "França",
    "Gabon": "Gabão",
    "Gambia": "Ga G",
    "Georgia": "Geórgia",
    "Germany": "Alemanha",
    "Ghana": "Gana",
    "Gibraltar": "Gibraltar",
    "Greece": "Gr G",
    "Greenland": "Groenlândia",
    "Grenada": "Granada",
    "Guatemala": "Guatemala",
    "Guinea": "Guiné",
    "Guinea-Bissau": "Guiné G G",
    "Guyana": "Guiana",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hong Kong": "Hong",
    "Hungary": "Hungria",
    "Iceland": "Islândia",
    "India": "Índia",
    "Indonesia": "Indonésia",
    "Iran": "Ir",
    "Iraq": "Iraque",
    "Ireland": "Irlanda",
    "Israel": "Israel",
    "Italy": "Itália",
    "Ivory Coast": "Costa C",
    "Jamaica": "Jamaica",
    "Japan": "Japão",
    "Jordan": "Jordânia",
    "Kazakhstan": "Cazaquistão",
    "Kenya": "Quénia",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Quirguistão",
    "Laos": "Laos",
    "Latvia": "Letónia",
    "Lebanon": "Líbano",
    "Lesotho": "Lesoto",
    "Liberia": "Libéria",
    "Libya": "Líbia",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lituânia",
    "Luxembourg": "Luxemburgo",
    "Macau": "Macau",
    "Madagascar": "Madagáscar",
    "Malawi": "Maláui",
    "Malaysia": "Malásia",
    "Maldives": "Maldivas",
    "Mali": "Mali",
    "Malta": "Malta",
    "Mauritania": "Mauritânia",
    "Mauritius": "Maurícia",
    "Mexico": "M M M M M M M M M M M M M",
    "Moldova": "Moldávia",
    "Monaco": "Mónaco",
    "Mongolia": "Mongólia",
    "Montenegro": "Montenegro",
    "Morocco": "Marrocos",
    "Mozambique": "Moçambique",
    "Myanmar": "Myanmar",
    "Namibia": "Namíbia",
    "Nepal": "Nepal",
    "Netherlands": "Holanda",
    "New Zealand": "Nova N",
    "Nicaragua": "Nicarágua",
    "Niger": "Nicarágua N",
    "Nigeria": "Nigéria",
    "North Korea": "Coreia",
    "North Macedonia": "Macedónia",
    "Northern Ireland": "Irlanda I",
    "Norway": "Noruega",
    "Oman": "Omã",
    "Pakistan": "Paquistão",
    "Palestine": "Palestina",
    "Panama": "Panamá",
    "Papua New Guinea": "Papua",
    "Paraguay": "Paraguai",
    "Peru": "Peru",
    "Philippines": "Filipinas",
    "Poland": "Polónia",
    "Portugal": "Portugal",
    "Puerto Rico": "Porto",
    "Qatar": "Catar",
    "Romania": "Roménia",
    "Russia": "Rússia",
    "Rwanda": "Ruanda",
    "San Marino": "San",
    "Saudi Arabia": "Arábia",
    "Scotland": "Escócia",
    "Senegal": "Senegal",
    "Serbia": "Sérvia",
    "Seychelles": "Seicheles",
    "Sierra Leone": "Serra",
    "Singapore": "Singapura",
    "Slovakia": "Eslováquia",
    "Slovenia": "Eslovénia",
    "Somalia": "Somália",
    "South Africa": "África",
    "South Korea": "Coreia C",
    "South Sudan": "Sudão S",
    "Spain": "Espanha",
    "Sri Lanka": "Sri Lanca",
    "Sudan": "Sudão",
    "Suriname": "Suriname",
    "Sweden": "Suécia",
    "Switzerland": "Suíça",
    "Syria": "Síria",
    "Taiwan": "Taiwan",
    "Tajikistan": "Tajiquistão",
    "Tanzania": "Tanzânia",
    "Thailand": "Tailândia",
    "Togo": "Togo",
    "Trinidad and Tobago": "Trindade e Tobago",
    "Tunisia": "Tunísia",
    "Turkey": "Turquia",
    "Turkmenistan": "Turquemenistão",
    "Uganda": "Uganda",
    "Ukraine": "Ucrânia",
    "United Arab Emirates": "Emirados Árabes Unidos",
    "United States": "EUA",
    "Uruguay": "Uruguai",
    "Uzbekistan": "Uzbequistão",
    "Vanuatu": "Vanuatu",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietname",
    "Wales": "País de Gales",
    "Yemen": "Iémen",
    "Zambia": "Zâmbia",
    "Zimbabwe": "Zimbábue"
}